using FEZSkillCounter.Extension;
using System.Collections.Generic;

using R = FEZSkillCounter.Properties.Resources;

namespace FEZSkillCounter
{
    public class SkillStorage
    {
        public static Dictionary<string, Skill> Table;

        public static void Create()
        {
            Table = new Dictionary<string, Skill>()
            {
                { R.Cestus_アースバインド.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_アースバインド), 42) },
                { R.Cestus_アースバインド_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_アースバインド_S), 42) },
                { R.Cestus_インテンスファイ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_インテンスファイ), 30) },
                { R.Cestus_インテンスファイ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_インテンスファイ_S), 30) },
                { R.Cestus_エナジースフィア.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_エナジースフィア), 25) },
                { R.Cestus_エナジースフィア_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_エナジースフィア_S), 25) },
                { R.Cestus_エンダーレイド.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_エンダーレイド), 10) },
                { R.Cestus_エンダーレイド_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_エンダーレイド_S), 10) },
                { R.Cestus_ゲイザースマッシュ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_ゲイザースマッシュ), 35) },
                { R.Cestus_ゲイザースマッシュ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_ゲイザースマッシュ_S), 35) },
                { R.Cestus_サイクロンディザスター.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_サイクロンディザスター), 46) },
                { R.Cestus_サイクロンディザスター_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_サイクロンディザスター_S), 46) },
                { R.Cestus_シャットアウト.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_シャットアウト), 60) },
                { R.Cestus_シャットアウト_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_シャットアウト_S), 60) },
                { R.Cestus_ショックウェイブ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_ショックウェイブ), 35) },
                { R.Cestus_ショックウェイブ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_ショックウェイブ_S), 35) },
                { R.Cestus_ソリッドストライク.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_ソリッドストライク), 36) },
                { R.Cestus_ソリッドストライク_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_ソリッドストライク_S), 36) },
                { R.Cestus_タワードミネーション.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_タワードミネーション), 25) },
                { R.Cestus_タワードミネーション_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_タワードミネーション_S), 25) },
                { R.Cestus_ドレインクロー.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_ドレインクロー), 24) },
                { R.Cestus_ドレインクロー_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_ドレインクロー_S), 24) },
                { R.Cestus_ノックインパクト.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_ノックインパクト), 34) },
                { R.Cestus_ノックインパクト_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_ノックインパクト_S), 34) },
                { R.Cestus_ハードレインフォース.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_ハードレインフォース), 40) },
                { R.Cestus_ハードレインフォース_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_ハードレインフォース_S), 40) },
                { R.Cestus_ハームアクティベイト.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_ハームアクティベイト), 24) },
                { R.Cestus_ハームアクティベイト_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_ハームアクティベイト_S), 24) },
                { R.Cestus_ホーネットスティング.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_ホーネットスティング), 25) },
                { R.Cestus_ホーネットスティング_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_ホーネットスティング_S), 25) },
                //{ R.Cestus_通常攻撃.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_通常攻撃), 0) },
                //{ R.Cestus_通常攻撃_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Cestus_通常攻撃_S), 0) },

                { R.Fencer_アクセラレーション.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_アクセラレーション), 25, 28) },
                { R.Fencer_アクセラレーション_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_アクセラレーション_S), 25, 28) },
                { R.Fencer_イレイスマジック.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_イレイスマジック), 30, 33) },
                { R.Fencer_イレイスマジック_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_イレイスマジック_S), 30, 33) },
                { R.Fencer_エリアルフォール.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_エリアルフォール), 25) },
                { R.Fencer_エリアルフォール_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_エリアルフォール_S), 25) },
                { R.Fencer_オブティンプロテクト.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_オブティンプロテクト), 25, 28) },
                { R.Fencer_オブティンプロテクト_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_オブティンプロテクト_S), 25, 28) },
                { R.Fencer_シャイニングクロス.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_シャイニングクロス), 24, 26, 28) },
                { R.Fencer_シャイニングクロス_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_シャイニングクロス_S), 24, 26, 28) },
                { R.Fencer_ストライクダウン.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_ストライクダウン), 20, 24, 28) },
                { R.Fencer_ストライクダウン_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_ストライクダウン_S), 20, 24, 28) },
                { R.Fencer_テンペストピアス.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_テンペストピアス), 28) },
                { R.Fencer_テンペストピアス_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_テンペストピアス_S), 28) },
                { R.Fencer_デュアルストライク.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_デュアルストライク), 20) },
                { R.Fencer_デュアルストライク_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_デュアルストライク_S), 20) },
                { R.Fencer_フィニッシュスラスト.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_フィニッシュスラスト), 50) },
                { R.Fencer_フィニッシュスラスト_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_フィニッシュスラスト_S), 50) },
                { R.Fencer_フラッシュスティンガー.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_フラッシュスティンガー), 30) },
                { R.Fencer_フラッシュスティンガー_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_フラッシュスティンガー_S), 30) },
                { R.Fencer_ペネトレイトスラスト.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_ペネトレイトスラスト), 28) },
                { R.Fencer_ペネトレイトスラスト_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_ペネトレイトスラスト_S), 28) },
                { R.Fencer_ラピッドファンデヴ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_ラピッドファンデヴ), 10, 14) },
                { R.Fencer_ラピッドファンデヴ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_ラピッドファンデヴ_S), 10, 14) },
                { R.Fencer_リバースキック.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_リバースキック), 16) },
                { R.Fencer_リバースキック_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_リバースキック_S), 16) },
                { R.Fencer_ヴィガーエイド.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_ヴィガーエイド), 25, 28) },
                { R.Fencer_ヴィガーエイド_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_ヴィガーエイド_S), 25, 28) },
                //{ R.Fencer_通常攻撃.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_通常攻撃), 0) },
                //{ R.Fencer_通常攻撃_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Fencer_通常攻撃_S), 0) },

                //{ R.Scout_アローレイン.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_アローレイン), 36) },
                //{ R.Scout_アローレイン_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_アローレイン_S), 36) },
                //{ R.Scout_アームブレイク.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_アームブレイク), 16) },
                //{ R.Scout_アームブレイク_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_アームブレイク_S), 16) },
                //{ R.Scout_イーグルショット.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_イーグルショット), 15) },
                //{ R.Scout_イーグルショット_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_イーグルショット_S), 15) },
                //{ R.Scout_エアレイド.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_エアレイド), 10) },
                //{ R.Scout_エアレイド_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_エアレイド_S), 10) },
                //{ R.Scout_ガードブレイク.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ガードブレイク), 14) },
                //{ R.Scout_ガードブレイク_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ガードブレイク_S), 14) },
                //{ R.Scout_クイックビート.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_クイックビート), 34) },
                //{ R.Scout_クイックビート_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_クイックビート_S), 34) },
                //{ R.Scout_クラッシュショット.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_クラッシュショット), 50) },
                //{ R.Scout_クラッシュショット_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_クラッシュショット_S), 50) },
                //{ R.Scout_コメットキャノン.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_コメットキャノン), 21) },
                //{ R.Scout_コメットキャノン_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_コメットキャノン_S), 21) },
                //{ R.Scout_スウィープキャノン.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_スウィープキャノン), 40) },
                //{ R.Scout_スウィープキャノン_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_スウィープキャノン_S), 40) },
                //{ R.Scout_スパイダーウェブ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_スパイダーウェブ), 18) },
                //{ R.Scout_スパイダーウェブ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_スパイダーウェブ_S), 18) },
                //{ R.Scout_ダガーストライク.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ダガーストライク), 22) },
                //{ R.Scout_ダガーストライク_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ダガーストライク_S), 22) },
                //{ R.Scout_トゥルーショット.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_トゥルーショット), 18) },
                //{ R.Scout_トゥルーショット_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_トゥルーショット_S), 18) },
                //{ R.Scout_ドッジシュート.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ドッジシュート), 28) },
                //{ R.Scout_ドッジシュート_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ドッジシュート_S), 28) },
                //{ R.Scout_ハイド.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ハイド), 32) },
                //{ R.Scout_ハイド_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ハイド_S), 32) },
                //{ R.Scout_バーストキャノン.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_バーストキャノン), 82) },
                //{ R.Scout_バーストキャノン_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_バーストキャノン_S), 82) },
                //{ R.Scout_パニッシングストライク.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_パニッシングストライク), 84) },
                //{ R.Scout_パニッシングストライク_D.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_パニッシングストライク_D), 84) },
                //{ R.Scout_パニッシングストライク_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_パニッシングストライク_S), 84) },
                //{ R.Scout_パワーシュート.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_パワーシュート), 32) },
                //{ R.Scout_パワーシュート_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_パワーシュート_S), 32) },
                //{ R.Scout_パワーブレイク.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_パワーブレイク), 12) },
                //{ R.Scout_パワーブレイク_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_パワーブレイク_S), 12) },
                //{ R.Scout_ピアッシングシュート.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ピアッシングシュート), 76) },
                //{ R.Scout_ピアッシングシュート_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ピアッシングシュート_S), 76) },
                //{ R.Scout_ファストショット.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ファストショット), 30) },
                //{ R.Scout_ファストショット_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ファストショット_S), 30) },
                //{ R.Scout_フリックショット.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_フリックショット), 22) },
                //{ R.Scout_フリックショット_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_フリックショット_S), 22) },
                //{ R.Scout_ブレイズショット.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ブレイズショット), 25) },
                //{ R.Scout_ブレイズショット_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ブレイズショット_S), 25) },
                //{ R.Scout_ホワイトバレット.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ホワイトバレット), 30) },
                //{ R.Scout_ホワイトバレット_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ホワイトバレット_S), 30) },
                //{ R.Scout_ポイズンショット.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ポイズンショット), 22) },
                //{ R.Scout_ポイズンショット_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ポイズンショット_S), 22) },
                //{ R.Scout_ポイズンブロウ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ポイズンブロウ), 12) },
                //{ R.Scout_ポイズンブロウ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ポイズンブロウ_S), 12) },
                //{ R.Scout_ラッシュバレット.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ラッシュバレット), 32) },
                //{ R.Scout_ラッシュバレット_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ラッシュバレット_S), 32) },
                //{ R.Scout_レッグブレイク.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_レッグブレイク), 15) },
                //{ R.Scout_レッグブレイク_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_レッグブレイク_S), 15) },
                //{ R.Scout_ヴァイパーバイト.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ヴァイパーバイト), 18) },
                //{ R.Scout_ヴァイパーバイト_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ヴァイパーバイト_S), 18) },
                //{ R.Scout_ヴォイドダークネス.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ヴォイドダークネス), 32) },
                //{ R.Scout_ヴォイドダークネス_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_ヴォイドダークネス_S), 32) },
                ////{ R.Scout_通常攻撃.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_通常攻撃), 0) },
                ////{ R.Scout_通常攻撃_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Scout_通常攻撃_S), 0) },

                { R.Sorcerer_アイスジャベリン.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_アイスジャベリン), 30) },
                { R.Sorcerer_アイスジャベリン_D.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_アイスジャベリン_D), 30) },
                { R.Sorcerer_アイスジャベリン_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_アイスジャベリン_S), 30) },
                { R.Sorcerer_アイスターゲット.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_アイスターゲット), 34) },
                { R.Sorcerer_アイスターゲット_D.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_アイスターゲット_D), 34) },
                { R.Sorcerer_アイスターゲット_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_アイスターゲット_S), 34) },
                { R.Sorcerer_アイスボルト.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_アイスボルト), 18) },
                { R.Sorcerer_アイスボルト_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_アイスボルト_S), 18) },
                { R.Sorcerer_エレキドライブ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_エレキドライブ), 36) },
                { R.Sorcerer_エレキドライブ_D.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_エレキドライブ_D), 36) },
                { R.Sorcerer_エレキドライブ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_エレキドライブ_S), 36) },
                { R.Sorcerer_グラビティキャプチャー.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_グラビティキャプチャー), 72) },
                { R.Sorcerer_グラビティキャプチャー_D.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_グラビティキャプチャー_D), 72) },
                { R.Sorcerer_グラビティキャプチャー_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_グラビティキャプチャー_S), 72) },
                { R.Sorcerer_サンダーボルト.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_サンダーボルト), 33) },
                { R.Sorcerer_サンダーボルト_D.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_サンダーボルト_D), 33) },
                { R.Sorcerer_サンダーボルト_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_サンダーボルト_S), 33) },
                { R.Sorcerer_ジャッジメントレイ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ジャッジメントレイ), 80) },
                { R.Sorcerer_ジャッジメントレイ_D.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ジャッジメントレイ_D), 80) },
                { R.Sorcerer_ジャッジメントレイ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ジャッジメントレイ_S), 80) },
                { R.Sorcerer_スパークフレア.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_スパークフレア), 65) },
                { R.Sorcerer_スパークフレア_D.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_スパークフレア_D), 65) },
                { R.Sorcerer_スパークフレア_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_スパークフレア_S), 65) },
                { R.Sorcerer_ファイア.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ファイア), 15) },
                { R.Sorcerer_ファイア_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ファイア_S), 15) },
                { R.Sorcerer_ファイアランス.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ファイアランス), 32) },
                { R.Sorcerer_ファイアランス_D.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ファイアランス_D), 32) },
                { R.Sorcerer_ファイアランス_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ファイアランス_S), 32) },
                { R.Sorcerer_フリージングウェイブ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_フリージングウェイブ), 44) },
                { R.Sorcerer_フリージングウェイブ_D.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_フリージングウェイブ_D), 44) },
                { R.Sorcerer_フリージングウェイブ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_フリージングウェイブ_S), 44) },
                { R.Sorcerer_フレイムサークル.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_フレイムサークル), 40) },
                { R.Sorcerer_フレイムサークル_D.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_フレイムサークル_D), 40) },
                { R.Sorcerer_フレイムサークル_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_フレイムサークル_S), 40) },
                { R.Sorcerer_ブリザードカレス.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ブリザードカレス), 68) },
                { R.Sorcerer_ブリザードカレス_D.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ブリザードカレス_D), 68) },
                { R.Sorcerer_ブリザードカレス_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ブリザードカレス_S), 68) },
                { R.Sorcerer_ヘルファイア.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ヘルファイア), 72) },
                { R.Sorcerer_ヘルファイア_D.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ヘルファイア_D), 72) },
                { R.Sorcerer_ヘルファイア_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ヘルファイア_S), 72) },
                { R.Sorcerer_メテオインパクト.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_メテオインパクト), 68) },
                { R.Sorcerer_メテオインパクト_D.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_メテオインパクト_D), 68) },
                { R.Sorcerer_メテオインパクト_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_メテオインパクト_S), 68) },
                { R.Sorcerer_ライトニング.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ライトニング), 18) },
                { R.Sorcerer_ライトニング_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ライトニング_S), 18) },
                { R.Sorcerer_ライトニングスピア.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ライトニングスピア), 32) },
                { R.Sorcerer_ライトニングスピア_D.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ライトニングスピア_D), 32) },
                { R.Sorcerer_ライトニングスピア_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_ライトニングスピア_S), 32) },
                { R.Sorcerer_レーザーブラスト.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_レーザーブラスト), 68) },
                { R.Sorcerer_レーザーブラスト_D.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_レーザーブラスト_D), 68) },
                { R.Sorcerer_レーザーブラスト_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_レーザーブラスト_S), 68) },
                { R.Sorcerer_詠唱.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_詠唱), 20) },
                { R.Sorcerer_詠唱_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_詠唱_S), 20) },
                //{ R.Sorcerer_通常攻撃.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_通常攻撃), 0) },
                //{ R.Sorcerer_通常攻撃_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Sorcerer_通常攻撃_S), 0) },

                { R.Warrior_アサルトエッジ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_アサルトエッジ), 42) },
                { R.Warrior_アサルトエッジ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_アサルトエッジ_S), 42) },
                { R.Warrior_アタックレインフォース.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_アタックレインフォース), 40) },
                { R.Warrior_アタックレインフォース_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_アタックレインフォース_S), 40) },
                { R.Warrior_アークスタンプ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_アークスタンプ), 36) },
                { R.Warrior_アークスタンプ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_アークスタンプ_S), 36) },
                { R.Warrior_エクステンブレイド.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_エクステンブレイド), 35) },
                { R.Warrior_エクステンブレイド_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_エクステンブレイド_S), 35) },
                { R.Warrior_エンダーペイン.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_エンダーペイン), 10) },
                { R.Warrior_エンダーペイン_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_エンダーペイン_S), 10) },
                { R.Warrior_ガードレインフォース.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ガードレインフォース), 40) },
                { R.Warrior_ガードレインフォース_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ガードレインフォース_S), 40) },
                { R.Warrior_クラックバング.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_クラックバング), 76) },
                { R.Warrior_クラックバング_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_クラックバング_S), 76) },
                { R.Warrior_クランブルストーム.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_クランブルストーム), 60) },
                { R.Warrior_クランブルストーム_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_クランブルストーム_S), 60) },
                { R.Warrior_シールドバッシュ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_シールドバッシュ), 40) },
                { R.Warrior_シールドバッシュ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_シールドバッシュ_S), 40) },
                { R.Warrior_ストライクスマッシュ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ストライクスマッシュ), 28) },
                { R.Warrior_ストライクスマッシュ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ストライクスマッシュ_S), 28) },
                { R.Warrior_スマッシュ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_スマッシュ), 12) },
                { R.Warrior_スマッシュ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_スマッシュ_S), 12) },
                { R.Warrior_スラムアタック.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_スラムアタック), 18) },
                { R.Warrior_スラムアタック_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_スラムアタック_S), 18) },
                { R.Warrior_ソニックブーム.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ソニックブーム), 15) },
                { R.Warrior_ソニックブーム_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ソニックブーム_S), 15) },
                { R.Warrior_ソリッドウォール.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ソリッドウォール), 50) },
                { R.Warrior_ソリッドウォール_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ソリッドウォール_S), 50) },
                { R.Warrior_ソードランページ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ソードランページ), 60) },
                { R.Warrior_ソードランページ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ソードランページ_S), 60) },
                { R.Warrior_ドラゴンテイル.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ドラゴンテイル), 60) },
                { R.Warrior_ドラゴンテイル_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ドラゴンテイル_S), 60) },
                { R.Warrior_フォースインパクト.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_フォースインパクト), 26) },
                { R.Warrior_フォースインパクト_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_フォースインパクト_S), 26) },
                { R.Warrior_ブレイズスラッシュ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ブレイズスラッシュ), 12) },
                { R.Warrior_ブレイズスラッシュ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ブレイズスラッシュ_S), 12) },
                { R.Warrior_ヘビースマッシュ.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ヘビースマッシュ), 34) },
                { R.Warrior_ヘビースマッシュ_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ヘビースマッシュ_S), 34) },
                { R.Warrior_ベヒモステイル.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ベヒモステイル), 32) },
                { R.Warrior_ベヒモステイル_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_ベヒモステイル_S), 32) },
                //{ R.Warrior_通常攻撃.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_通常攻撃), 0) },
                //{ R.Warrior_通常攻撃_S.SHA1Hash(), Skill.CreateFromResourceFileName(nameof(R.Warrior_通常攻撃_S), 0) },
            };
        }
    }
}
