// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryService;

namespace RepositoryService.Migrations
{
    [DbContext(typeof(SkillCountDbContext))]
    partial class SkillCountDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("RepositoryService.Entity.SkillCountDetailEntity", b =>
                {
                    b.Property<int>("SkillCountDetailId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<int?>("SkillCountEntitySkillCountId");

                    b.Property<string>("SkillName");

                    b.Property<string>("SkillShortName");

                    b.HasKey("SkillCountDetailId");

                    b.HasIndex("SkillCountEntitySkillCountId");

                    b.ToTable("SkillCountDetailEntity");
                });

            modelBuilder.Entity("RepositoryService.Entity.SkillCountEntity", b =>
                {
                    b.Property<int>("SkillCountId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MapName");

                    b.Property<DateTime>("RecordDate");

                    b.Property<string>("WorkName");

                    b.HasKey("SkillCountId");

                    b.ToTable("SkillCountDbSet");
                });

            modelBuilder.Entity("RepositoryService.Entity.SkillCountDetailEntity", b =>
                {
                    b.HasOne("RepositoryService.Entity.SkillCountEntity")
                        .WithMany("Details")
                        .HasForeignKey("SkillCountEntitySkillCountId");
                });
#pragma warning restore 612, 618
        }
    }
}
